export const menuArray = [
  {
    id: 1,
    category: "Pizza",
    name: "ДЕРЕВЕНСКАЯ",
    description: "САЛЯМИ, МОЦАРЕЛЛА, КОРНИШОНЫ, ЛУК КРАСНЫЙ, КУРИЦА КОПЧЁНАЯ",
    price: 480,
    imageUrl: "assets/1MENUImages/1-деревенская.jpg",
  },
  {
    id: 2,
    category: "Pizza",
    name: "ПЕПЕРОННИ",
    description: "МОЦАРЕЛЛА, ПОМИДОРЫ, САЛЯМИ ",
    price: 500,
    imageUrl: "assets/1MENUImages/3-пеперонни.png"
  },
  {
    id: 3,
    category: "Pizza",
    name: "ВЕТЧИНА-ГРИБЫ",
    description: "ВЕТЧИНА, МОЦАРЕЛЛА, ШАМПИНЬОНЫ",
    price: 450,
    imageUrl: "assets/1MENUImages/2-ветчинагрибы.jpg",
  },
  {
    id: 4,
    category: "Pizza",
    name: "БАРБЕКЮ",
    description: "ОХОТНИЧЬИ КОЛБАСКИ, СОУС БАРБЕКЮ, КОРНИШОНЫ, МОЦАРЕЛЛА, САЛЯМИ, БЕКОН",
    price: 520,
    imageUrl: "assets/1MENUImages/4-барбекю.jpg",
  },
  {
    id: 5,
    category: "Pizza",
    name: "4 МЯСА",
    description: "КУРИЦА КОПЧЁНАЯ, МОЦАРЕЛЛА, ВЕТЧИНА, САЛЯМИ, БЕКОН",
    price: 550,
    imageUrl: "assets/1MENUImages/5-4мяса.jpg",
  },
  {
    id: 6,
    category: "Pizza",
    name: "КАРБОНАРА",
    description: "БЕКОН, ВЕТЧИНА, МОЦАРЕЛЛА, ШАМПИНЬОНЫ",
    price: 525,
    imageUrl: "assets/1MENUImages/6-карбонара.png",
  },
  {
    id: 7,
    category: "Pizza",
    name: "МАРИНАРА",
    description: "МОРСКОЙ КОКТЕЙЛЬ, МОЦАРЕЛЛА, ОЛИВКИ",
    price: 600,
    imageUrl: "assets/1MENUImages/7-маринара.png",
  },
  {
    id: 8,
    category: "Pizza",
    name: "ЦЕЗАРЬ",
    description: "КОПЧЁНАЯ КУРИЦА, МОЦАРЕЛЛА, ЛИСТЬЯ САЛАТА, ПОМИДОР, СОУС ЦЕЗАРЬ, СРЕДИЗЕМНОМОРСКИЕ ТРАВЫ",
    price: 550,
    imageUrl: "assets/1MENUImages/8-цезарь.png",
  },
  {
    id: 9,
    category: "Pizza",
    name: "ГАВАЙСКАЯ",
    description: "АНАНАС, МОЦАРЕЛЛА, КОПЧЁНАЯ КУРИЦА",
    price: 500,
    imageUrl: "assets/1MENUImages/9-гавайская.png",
  },
  {
    id: 10,
    category: "Pizza",
    name: "4 СЫРА",
    description: "СЫР МОЦАРЕЛЛА, СЫР МААСДАМ, СЫР ДОР БЛЮ, СЫР ЧЕДДЕР",
    price: 550,
    imageUrl: "assets/1MENUImages/10-4сыра.png",
  },
  {
    id: 11.1,
    category: "Rolls",
    name: "ТЕМПУРА ЛАВА",
    description: "КРЕВЕТКА/, КРЕМ СЫР/, ЛОСОСЬ/, КРАБ/, СЫР СЛИВОЧНЫЙ",
    price: 400/320/380/340,
    imageUrl: "assets/1MENUImages/1-темпуралава.jpg",
  },
   {
    id: 12.1,
    category: "Rolls",
    name: "ТЕМПУРА ВУЛКАН 🌶️",
    description: "КРЕВЕТКА/, ЛОСОС/, УГОРЬ/, СЫР СЛИВОЧНЫЙ",
    price: 500/450/550,
    imageUrl: "assets/1MENUImages/2-темпуравулкан.jpg",
  },
  {
    id: 13,
    category: "Rolls",
    name: "ТЕМПУРА МИКС",
    description: "СЫР СЛИВОЧНЫЙ, СЫР СЛАЙСОВЫЙ, ОГУРЕЦ, КУНЖУТ, ЛОСОСЬ, УГОРЬ",
    price: 420,
    imageUrl: "assets/1MENUImages/3-темпурамикс.jpg",
  },
  {
    id: 14,
    category: "Rolls",
    name: "ТЕМПУРА ЧИЗ ХОТ 🌶️",
    description: "СЫР СЛИВОЧНЫЙ, СЫР СЛАЙСОВЫЙ, СЫР МОЦАРЕЛЛА",
    price: 250,
    imageUrl: "assets/1MENUImages/4-темпурачизхот.jpg",
  },
  {
    id: 15,
    category: "Rolls",
    name: "ТЕМПУРА ЧИКЕН ХОТ ",
    description: "КУРИЦА КОПЧЁНАЯ, СЫР СЛАЙСОВЫЙ, СЫР СЛИВОЧНЫЙ",
    price: 250,
    imageUrl: "assets/1MENUImages/5-темпурачикенхот.jpg",
  },
  {
    id: 16,
    category: "Rolls",
    name: "БИГ ТЕМПУРА 🌶️",
    description: "ЛОСОСЬ ЖАРЕНЫЙ, 3 СОУСА, КУНЖУТ, ОГУРЕЦ, КРАБ",
    price: 400,
    imageUrl: "assets/1MENUImages/6-бигтемпура.jpg",
  },
  {
    id: 17,
    category: "Rolls",
    name: "ТЕМПУРА ЭБИ ХОТ ",
    description: "СЫР СЛИВОЧНЫЙ, ИКРА МАСАГА, КРЕВЕТКА, ОГУРЕЦ",
    price: 400,
    imageUrl: "assets/1MENUImages/7-темпураэбихот.jpg",
  },
  {
    id: 18,
    category: "Rolls",
    name: "ТЕМПУРА УНАГИ",
    description: "СЫР СЛИВОЧНЫЙ, ОГУРЕЦ, КУНЖУТ, УГОРЬ",
    price: 400,
    imageUrl: "assets/1MENUImages/8-темпураунаги.jpg",
  },
  {
    id: 19,
    category: "Rolls",
    name: "ТЕМПУРА НЕЖНЫЙ",
    description: "КРЕВЕТКА, КРАБ",
    price: 380,
    imageUrl: "assets/1MENUImages/9-темпуранежный.jpg",
  },
  {
    id: 20,
    category: "Rolls",
    name: "ЭБИ ЧИРАЗИ",
    description: "СЫР СЛИВОЧНЫЙ, КРЕВЕТКА, ЗАМЕС ЧИРАЗИ",
    price: 440,
    imageUrl: "assets/1MENUImages/10-эбичирази.jpg",
  },
  {
    id: 21,
    category: "Rolls",
    name: "ДИНАМИТ 🌶️",
    description: "СЫР СЛИВОЧНЫЙ, СЫР СЛАЙСОВЫЙ, ЛОСОСЬ, ОГУРЕЦ",
    price: 340,
    imageUrl: "assets/1MENUImages/11-динамит.jpg",
  },
  {
    id: 22,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ",
    description: "ЛОСОСЬ НАРЕЗКА, СЫР СЛИВОЧНЫЙ",
    price: 550,
    imageUrl: "assets/1MENUImages/12-филадельфия.jpg",
  },
  {
    id: 23,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ С ОГУРЦОМ",
    description: "ЛОСОСЬ НАРЕЗКА, СЫР СЛИВОЧНЫЙ, ОГУРЕЦ НАРЕЗКА",
    price: 550,
    imageUrl: "assets/1MENUImages/13-филадельфиясогурцом.jpg",
  },
  {
    id: 24,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ С УГРЁМ",
    description: "УГОРЬ НАРЕЗКА, СЫР СЛИВОЧНЫЙ, ОГУРЕЦ НАРЕЗКА, КУНЖУТ",
    price: 600,
    imageUrl: "assets/1MENUImages/14-филадельфиясугрем.jpg",
  },
  {
    id: 25,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ С ЛУКОМ",
    description: "ЛОСОСЬ НАРЕЗКА, СЫР СЛИВОЧНЫЙ, ЛУК ЗЕЛЁНЫЙ",
    price: 550,
    imageUrl: "assets/1MENUImages/15-филадельфияслуком.jpg",
  },
  {
    id: 26,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ ЛЮКС",
    description: "ОГУРЕЦ НАРЕЗКА, ЛОСОСЬ НАРЕЗКА, УГОРЬ НАРЕЗКА, СЫР СЛИВОЧНЫЙ",
    price: 580,
    imageUrl: "assets/1MENUImages/16-филадельфиялюкс.jpg",
  },
  {
    id: 27,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ ЛАЙТ",
    description: "СЫР СЛИВОЧНЫЙ, ЛОСОСЬ НАРЕЗКА, ОГУРЕЦ НАРЕЗКА",
    price: 420,
    imageUrl: "assets/1MENUImages/17-филадельфиялайт.jpg",
  },
  {
    id: 28.1,
    category: "Rolls",
    name: "ЗАПЕЧЁННЫЙ С ШИИТАКИ",
    description: "ЛОСОСЬ/, КУРИЦА/, УГОРЬ НАРЕЗКА/, СЫР СЛИВОЧНЫЙ, ШИИТАКИ ГРИБЫ, СЫР ЗАМЕС",
    price: 340/300/300,
    imageUrl: "assets/1MENUImages/18-запечённыйсшиитаки.jpg",
  },
  {
    id: 29,
    category: "Rolls",
    name: "КАЛИФОРНИЯ КУНЖУТ",
    description: "КРАБ ЗАМЕС, ОГУРЕЦ, КУНЖУТ",
    price: 260,
    imageUrl: "assets/1MENUImages/19-калифорниякунжут.jpg",
  },
  {
    id: 30,
    category: "Rolls",
    name: "КАЛИФОРНИЯ ЛЮКС",
    description: "ОГУРЕЦ НАРЕЗКА, ИКРА МАСАГА, КРЕВЕТКА ",
    price: 380,
    imageUrl: "assets/1MENUImages/20-калифорниялюкс.jpg",
  },
  {
    id: 31,
    category: "Rolls",
    name: "КАЛИФОРНИЯ КРАБ",
    description: "ИКРА МАСАГА, КРАБ ЗАМЕС, ОГУРЕЦ",
    price: 300,
    imageUrl: "assets/1MENUImages/21-калифорниякраб.jpg",
  },
  {
    id: 32,
    category: "Rolls",
    name: "КАНАДСКИЙ",
    description: "СЫР СЛИВОЧНЫЙ, ОГУРЕЦ НАРЕЗКА, УГОРЬ НАРЕЗКА, КУНЖУТ, ЛОСОСЬ",
    price: 540,
    imageUrl: "assets/1MENUImages/22-канадский.jpg",
  },
  {
    id: 33,
    category: "Rolls",
    name: "СПАЙСИ РОЛЛ 🌶️",
    description: "ЛОСОСЬ ЖАРЕНЫЙ, СЫР СЛИВОЧНЫЙ, ОГУРЕЦ",
    price: 300,
    imageUrl: "assets/1MENUImages/23-спайсиролл.jpg",
  },
  {
    id: 34,
    category: "Rolls",
    name: "ТЕРИ МАКИ",
    description: "ОГУРЕЦ НАРЕЗКА, ЛОСОСЬ ЖАРЕНЫЙ, СЫР СЛИВОЧНЫЙ, КУНЖУТ",
    price: 240,
    imageUrl: "assets/1MENUImages/24-теримаки.jpg",
  },
  {
    id: 35,
    category: "Rolls",
    name: "КИМЧИ МАКИ 🌶️",
    description: "ОГУРЕЦ НАРЕЗКА, ЛОСОСЬ ЖАРЕНЫЙ, СЫР СЛИВОЧНЫЙ",
    price: 240,
    imageUrl: "assets/1MENUImages/25-кимчимаки.jpg",
  },
  {
    id: 36,
    category: "Rolls",
    name: "ЭБИ МАКИ",
    description: "ОГУРЕЦ НАРЕЗКА, КРЕВЕТКА",
    price: 260,
    imageUrl: "assets/1MENUImages/26эбимаки.jpg",
  },
  {
    id: 37,
    category: "Rolls",
    name: "УНАГИ МАКИ",
    description: "УГОРЬ ВНУТРИ, ОГУРЕЦ НАРЕЗКА, КУНЖУТ",
    price: 300,
    imageUrl: "assets/1MENUImages/27-унагимаки.jpg",
  },
  {
    id: 38,
    category: "Rolls",
    name: "ЯСАЙ МАКИ",
    description: "СЫР СЛИВОЧНЫЙ, ОГУРЕЦ НАРЕЗКА, ТОМАТ КАНКАССЕ, ПЕРЕЦ БОЛГАРСКИЙ",
    price: 220,
    imageUrl: "assets/1MENUImages/28-ясаймаки.jpg",
  },
  {
    id: 39,
    category: "Rolls",
    name: "КАППА МАКИ",
    description: "КУНЖУТ, ОГУРЕЦ",
    price: 150,
    imageUrl: "assets/1MENUImages/29-каппамаки.jpg",
  },
  {
    id: 40,
    category: "Rolls",
    name: "НЕЖНОСТЬ",
    description: "КРАБ ЗАМЕС, КРЕВЕТКА, ОГУРЕЦ НАРЕЗКА, ИКРА МАСАГА, КУНЖУТ",
    price: 400,
    imageUrl: "assets/1MENUImages/30-нежность.jpg",
  },
  {
    id: 41,
    category: "Rolls",
    name: "БОНИТО",
    description: "ОГУРЕЦ НАРЕЗКА, ЛОСОСЬ ЖАРЕНЫЙ, СТРУЖКА ТУНЦА, СЫР СЛИВОЧНЫЙ",
    price: 280,
    imageUrl: "assets/1MENUImages/31-бонито.jpg",
  },
  {
    id: 42.1,
    category: "Rolls",
    name: "Лава",
    description: "ЛОСОСЬ/, КРАБ/, КРЕВЕТКА/, КРЕМ СЫР/",
    price: 340/280/500/250,
    imageUrl: "assets/1MENUImages/32-лава.jpg",
  },
  {
    id: 43,
    category: "Rolls",
    name: "ГЕЙША",
    description: "ОГУРЕЦ НАРЕЗКА, СЫР СЛИВОЧНЫЙ, ИКРА МАСАГА, ЛОСОСЬ",
    price: 300,
    imageUrl: "assets/1MENUImages/33-гейша.jpg",
  },
  {
    id: 44,
    category: "Rolls",
    name: "ВОСХОД",
    description: "ОГУРЕЦ НАРЕЗКА, СЫР СЛИВОЧНЫЙ, ИКРА МАСАГА, КРЕВЕТКА",
    price: 290,
    imageUrl: "assets/1MENUImages/34-восход.jpg",
  },
  {
    id: 45,
    category: "Rolls",
    name: "СЯКЕ МАКИ",
    description: "ОГУРЕЦ НАРЕЗКА, ЛОСОСЬ",
    price: 250,
    imageUrl: "assets/1MENUImages/35-сякемаки.jpg",
  },
  {
    id: 46,
    category: "Rolls",
    name: "ТОБИ ЧИЗ",
    description: "ОГУРЕЦ НАРЕЗКА, СЫР СЛИВОЧНЫЙ, ИКРА МАСАГА",
    price: 250,
    imageUrl: "assets/1MENUImages/36-тобичиз.jpg",
  },
  {
    id: 47,
    category: "Rolls",
    name: "ЧИКЕН МАКИ 🌶️",
    description: "КУРИЦА КОПЧЁНАЯ, ОГУРЕЦ НАРЕЗКА, СЫР СЛИВОЧНЫЙ, СЫР СЛАЙСОВЫЙ",
    price: 250,
    imageUrl: "assets/1MENUImages/37-чикенмаки.jpg",
  },
  {
    id: 48,
    category: "Rolls",
    name: "КРАБИ СПАЙС 🌶️",
    description: "СЫР СЛИВОЧНЫЙ, КРАБ ЗАМЕС",
    price: 180,
    imageUrl: "assets/1MENUImages/38-крабиспайс.jpg",
  },
  {
    id: 49,
    category: "Rolls",
    name: "ТОМАТОС МАКИ",
    description: "СЫР СЛИВОЧНЫЙ, ТОМАТ КАНКАССЕ",
    price: 150,
    imageUrl: "assets/1MENUImages/39-томатосмаки.jpg",
  },
  {
    id: 50.1,
    category: "Rolls",
    name: "ЗАПЕЧЁННЫЙ ВУЛКАН 🌶️",
    description: "ЛОСОСЬ/, УГОРЬ/, КРЕВЕТКА/, СЫР СЛИВОЧНЫЙ",
    price: 450/550/500,
    imageUrl: "assets/1MENUImages/40-запечённыйвулкан.jpg",
  },
  {
    id: 51.1,
    category: "Rolls",
    name: "ЗАПЕЧЁННЫЙ СПАЙСИ 🌶️",
    description: "ЛОСОСЬ/, КРЕВЕТКА/, КРАБ/, УГОРЬ/, СЫР СЛИВОЧНЫЙ, СЫР ЗАМЕС",
    price: 340/380/280/440,
    imageUrl: "assets/1MENUImages/41-запечённыйспайси.jpg",
  },
  {
    id: 52.1,
    category: "Rolls",
    name: "ЗАПЕЧЁННЫЙ РОЛЛ",
    description: "ЛОСОСЬ/, КРЕВЕТКА/, КРАБ/, УГОРЬ/, СЫР СЛИВОЧНЫЙ, СЫР ЗАМЕС, КУНЖУТ",
    price: 420,
    imageUrl: "assets/1MENUImages/42-запечённыйролл.jpg",
  },
  {
    id: 53.1,
    category: "Rolls",
    name: "ВУЛКАН 🌶️",
    description: "ЛОСОСЬ/, УГОРЬ/, КРЕВЕТКА/, СЫР СЛИВОЧНЫЙ",
    price: 450/550/500,
    imageUrl: "assets/1MENUImages/43-вулкан.jpg",
  },
  {
    id: 54,
    category: "Sets",
    name: 'СЕТ “ХИТ”',
    description: "ТОБИ ЧИЗ, ВОСХОД, БОНИТО, НАБОР: 1",
    price: 900,
    imageUrl: 'assets/1MENUImages/100_СЕТ_“ХИТ”.jpg',
  },
  {
    id: 55,
    category: "Sets",
    name: '“ВЕГЕТЕРИАНСКИЙ”',
    description: "ТОМАТОС МАКИ, КАПА МАКИ, ЯСАЙ МАКИ, НАБОР: 1",
    price: 650,
    imageUrl: 'assets/1MENUImages/101_“ВЕГЕТЕРИАНСКИЙ”.jpg',
  },
  {
    id: 56,
    category: "Sets",
    name: 'СЕТ “ЭЛИТ”',
    description: "ФИЛА КЛАССИЧЕСКАЯ, ЛАВА КРАБ, КАЛИФОРНИЯ ЛЮКС, НАБОР: 2",
    price: 1400,
    imageUrl: 'assets/1MENUImages/102_СЕТ_“ЭЛИТ”.jpg',
  },
  {
    id: 57,
    category: "Sets",
    name: 'СЕТ “КЛАССИК”',
    description: "ФИЛА С ОГУРЦОМ, КАЛИФОРНИЯ КРАБ, КАНАДСКИЙ РОЛЛ, НАБОР: 2",
    price: 1500,
    imageUrl: 'assets/1MENUImages/103_СЕТ_“КЛАССИК”.jpg',
  },
  {
    id: 58,
    category: "Sets",
    name: '“ТЕМПУРА ЖАРЕНЫЙ”',
    description: "ТЕМПУРА ЛАВА С КРЕВЕТКОЙ, ТЕМПУРА ЛЮКС, БИГ ТЕМПУРА, ДИНАМИТ, НАБОР: 2",
    price: 1800,
    imageUrl: 'assets/1MENUImages/104_“ТЕМПУРА_ЖАРЕНЫЙ”.jpg',
  },
  {
    id: 59,
    category: "Sets",
    name: 'СЕТ “WAUKESHA”',
    description: "КРАБИ СПАЙС, ЭБИ МАКИ, ЧИКЕН ХОТ, НАБОР: 1",
    price: 690,
    imageUrl: 'assets/1MENUImages/105_СЕТ_“WAUKESHA”.jpg',
  },
  {
    id: 60,
    category: "Sets",
    name: 'СЕТ “ХИТ-ХОТ”',
    description: "ТЕМПУРА ЛАВА С ЛОСОСЕМ, ТЕМПУРА ЧИКЕН ХОТ, ТЕМПУРА ЧИЗ ХОТ, ТЕМПУРА УНАГИ, СПАЙСИ РОЛЛ, НАБОР: 3",
    price: 1700,
    imageUrl: 'assets/1MENUImages/106_СЕТ_“ХИТ-ХОТ”.jpg',
  },
  {
    id: 61,
    category: "Sets",
    name: 'СЕТ “ASSORTI"',
    description: "ЗАПЕЧЁННЫЙ ВУЛКАН С КРЕВЕТКОЙ, ТЕМПУРА ЛАВА КРАБ, ТЕМПУРА ЧИЗ ХОТ, СПАЙСИ С ЛОСОСЕМ, КРАБ СПАЙСИ, ЛАВА ЛОСОСЬ, НАБОР: 4",
    price: 1950,
    imageUrl: 'assets/1MENUImages/107_СЕТ_“ASSORTI".jpg',
  },
  {
    id: 62,
    category: "Sets",
    name: '“ЖАРЕНО-ЗАПЕЧЁННЫЙ”',
    description: "ЗАПЕЧЁННЫЙ СПАЙСИ С ЛОСОСЕМ, ЗАПЕЧЁННЫЙ С КРЕВЕТКОЙ, ТЕМПУРА ЛЮКС, ДИНАМИТ, НАБОР: 2",
    price: 1550,
    imageUrl: 'assets/1MENUImages/108_“ЖАРЕНО-ЗАПЕЧЁННЫЙ”.jpg',
  },
  {
    id: 63,
    category: "Sets",
    name: '“ФИЛАДЕЛЬФИЯ ЛЮКС”',
    description: "ФИЛАДЕЛЬФИЯ КЛАССИЧЕСКАЯ, ФИЛАДЕЛЬФИЯ С УГРЁМ, ФИЛАДЕЛЬФИЯ ЛАЙТ, НАБОР: 2",
    price: 1700,
    imageUrl: 'assets/1MENUImages/109_“ФИЛАДЕЛЬФИЯ_ЛЮКС”.jpg',
  },
  {
    id: 64,
    category: "Sets",
    name: 'СЕТ “VIKTORI”',
    description: "КАЛИФОРНИЯ В КУНЖУТЕ, ТОМАТОС МАКИ, КРАБ СПАЙСИ, КИМЧИ МАКИ, ТЕРИ МАКИ, СЯКЕ МАКИ, ЭБИ МАКИ, БОНИТО, ВОСХОД, НАБОР: 4",
    price: 2100,
    imageUrl: 'assets/1MENUImages/110_СЕТ_“VIKTORI”.jpg',
  },
  {
    id: 65,
    category: "Sets",
    name: 'СЕТ “ИМПЕРИАЛ"',
    description: "ЗАПЕЧЁННЫЙ СПАЙСИ С КРЕВЕТКОЙ, ЗАПЕЧЁННЫЙ С ЛОСОСЕМ, ТЕМПУРА ЭБИ ХОТ, КАНАДСКИЙ РОЛЛ, СПАЙСИ РОЛЛ, НЕЖНОСТЬ, ЧИКЕН МАКИ, КАЛИФОРНИЯ В КУНЖУТЕ, НАБОР: 4",
    price: 2998,
    imageUrl: 'assets/1MENUImages/111_СЕТ_“ИМПЕРИАЛ".jpg',
  },
  {
    id: 66,
    category: "WOK",
    name: "КАРБОНАРА",
    description: "ФЕТУЧИНИ ВАРЕНЫЙ, МОЦАРЕЛЛА, ВЕТЧИНА, СЛИВКИ, ЖЕЛТОК, БЕКОН",
    price: 450,
    imageUrl: 'assets/1MENUImages/115_карбонара.jpg',
  },
  {
    id: 67.1,
    category: "WOK",
    name: "ОСТРЫЙ ВОК",
    description: "ГОВЯДИНА/, СВИНИНА/, КУРИЦА/, ЛАПША НА ВЫБОР(!), ЛУК КРАСНЫЙ, ШИИТАКИ ГРИБЫ ВАРЕНЫЕ, ФАСОЛЬ СТРУЧКОВАЯ, ПЕРЕЦ БОЛГАРСКИЙ, СОУС КИМЧИ, СОУС АРОЙД",
    price: 400/375/350,
    imageUrl: 'assets/1MENUImages/116_острый_вок.jpg',
  },
  {
    id: 68.1,
    category: "WOK",
    name: "ВОК С ТЕРИЯКИ",
    description: "ГОВЯДИНА/, СВИНИНА/, КУРИЦА/, ЛАПША НА ВЫБОР, ЛУК КРАСНЫЙ, ФАСОЛЬ СТРУЧКОВАЯ, ПЕРЕЦ БОЛГАРСКИЙ, СОЕВЫЙ СОУС, СОУС ТЕРИЯКИ, ЧЕСНОК/ИМБИРЬ",
    price: 400/375/350,
    imageUrl: "assets/1MENUImages/117_вок_с_терияки.jpg",
  },
  {
    id: 69,
    category: "Grill House",
    name: "КАРТОФЕЛЬ МОЛОДОЙ В СПЕЦИЯХ",
    description: "150гр",
    price: 185,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 70,
    category: "Grill House",
    name: "КАРТОФЕЛЬ МОЛОДОЙ В КОЖУРЕ",
    description: "150гр",
    price: 185,
    imageUrl: "https://your-cdn.com/images/sesame.jpg",
  },
  {
    id: 71,
    category: "Grill House",
    name: "КАРТОФЕЛЬ ФРИ",
    description: "150гр",
    price: 185,
    imageUrl: "https://your-cdn.com/images/philadelphia-eel.jpg",
  },
  {
    id: 72,
    category: "Grill House",
    name: "КОЛЬЦА ЛУКОВЫЕ",
    description: "100гр",
    price: 105,
    imageUrl: "https://your-cdn.com/images/philadelphia-onion.jpg",
  },
  {
    id: 73,
    category: "Grill House",
    name: "КОЛЬЦА КАЛЬМАРА",
    description: "60гр",
    price: 150,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 74,
    category: "Grill House",
    name: "КРЫЛЫШКИ К ПИВУ",
    description: "150гр",
    price: 225,
    imageUrl: "https://your-cdn.com/images/sliced-salmon.jpg",
  },
  {
    id: 75,
    category: "Grill House",
    name: "КОЛБАСКА ГРИЛЬ",
    description: "75гр",
    price: 95,
    imageUrl: "https://your-cdn.com/images/sliced-eel.jpg",
  },
  {
    id: 76,
    category: "Grill House",
    name: "КУРИЦА ГРИЛЬ",
    description: "1кг",
    price: 650,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 77,
    category: "Grill House",
    name: "СЫРНЫЕ ШАРИКИ",
    description: "200гр",
    price: 200,
    imageUrl: "https://your-cdn.com/images/philadelphia.jpg",
  },
  {
    id: 78,
    category: "Grill House",
    name: "НАГГЕТСЫ",
    description: "230гр",
    price: 199,
    imageUrl: "https://your-cdn.com/images/sliced-salmon.jpg",
  },
  {
    id: 79,
    category: "Grill House",
    name: "СТРИПСЫ",
    description: "150гр",
    price: 225,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 80,
    category: "Shawarma",
    name: "ЦАРСКАЯ",
    description: "ЛАВАШ, МЯСО КУРИЦЫ, КАПУСТА, МОРКОВЬ ПО-КОРЕЙСКИ, КАРТОФЕЛЬ ФРИ, ТОМАТНЫЙ СОУС",
    price: 190/210/240,
    imageUrl: "https://your-cdn.com/images/philadelphia-luxe.jpg",
  },
  {
    id: 81,
    category: "Shawarma",
    name: "ГРИБНАЯ",
    description: "ЛАВАШ, МЯСО КУРИЦЫ, МАРИНОВАННЫЙ КРЫМСКИЙ ЛУК, ЖАРЕННЫЕ ШАМПИНЬОНЫ, КАРТОФЕЛЬ ФРИ, СВЕЖИЙ ОГУРЕЦ, ГРИБНОЙ СОУС",
    price: 210/230/270,
    imageUrl: "https://your-cdn.com/images/philadelphia-light.jpg",
  },
  {
    id: 82,
    category: "Shawarma",
    name: "СЫРНАЯ",
    description: "ЛАВАШ, МЯСО КУРИЦЫ, КАРТОФЕЛЬ ФРИ, КАПУСТА, СЫР, СВЕЖИЙ ОГУРЕЦ, СЫРНЫЙ СОУС",
    price: 210/230/270,
    imageUrl: "https://your-cdn.com/images/masago-caviar.jpg",
  },
  {
    id: 83,
    category: "Shawarma",
    name: "ПЕППЕРОНИ",
    description: "ЛАВАШ, ПЕППЕРОНИ, МОРКОВЬ ПО-КОРЕЙСКИ, КАРТОФЕЛЬ ФРИ, ПОМИДОРЫ, МАРИНОВАННЫЕ ОГУРЦЫ, ТОМАТНЫЙ СОУС",
    price: 250/310/370,
    imageUrl: "https://your-cdn.com/images/crab-mix.jpg",
  },
  {
    id: 84,
    category: "Shawarma",
    name: "ГАВАЙСКАЯ",
    description: " ЛАВАШ, МЯСО КУРИЦЫ, КАРТОФЕЛЬ ФРИ, АНАНАС, СЫР, ПЕКИНСКАЯ КАПУСТА, СОУС",
    price: 230/245/270,
    imageUrl: "https://your-cdn.com/images/cucumber.jpg",
  },
  {
    id: 85,
    category: "Shawarma",
    name: "МЯСНАЯ",
    description: "ЛАВАШ, СВИНИНА В ПАНИРОВКЕ, ТОМАТЫ, ОГУРЕЦ, КАРТОФЕЛЬ ФРИ, СЫРНЫЙ СОУС",
    price: 250/310/370,
    imageUrl: "https://your-cdn.com/images/crab-mix.jpg",
  },
  {
    id: 86,
    category: "Shawarma",
    name: "КРАБОВАЯ",
    description: "ЛАВАШ, КРАБОВОЕ МЯСО, МАРИНОВАННЫЙ ЛУК, ОГУРЕЦ, МОРКОВЬ, КАПУСТА, СОУС/МАЙОНЕЗ И СОЕВЫЙ",
    price: 230/280/320,
    imageUrl: "https://your-cdn.com/images/cucumber.jpg",
  },
  {
    id: 87,
    category: "Hot-Dog",
    name: "КЛАССИЧЕСКИЙ",
    description: "БУЛОЧКА, САРДЕЛЬКА-ГРИЛЬ, СВЕЖИЙ ОГУРЕЦ, БЕЛЫЙ СОУС, КРАСНЫЙ СОУС",
    price: 165,
    imageUrl: "https://your-cdn.com/images/sesame.jpg",
  },
  {
    id: 88,
    category: "Hot-Dog",
    name: "ФРАНЦУЗСКИЙ",
    description: "БУЛОЧКА, САРДЕЛЬКА-ГРИЛЬ, ТОМАТЫ, СЫР, БЕЛЫЙ СОУС, КРАСНЫЙ СОУС",
    price: 175,
    imageUrl: "https://your-cdn.com/images/california-sesame.jpg",
  },
  {
    id: 89,
    category: "Hot-Dog",
    name: "НЕМЕЦКИЙ",
    description: "БУЛОЧКА, САРДЕЛЬКА-ГРИЛЬ, МАРИНОВАННЫЙ ОГУРЕЦ, МАРИНОВАННЫЙ ЛУК, БЕЛЫЙ СОУС, КРАСНЫЙ СОУС, ДИЖОНСКАЯ ГОРЧИЦА",
    price: 185,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 90,
    category: "Hot-Dog",
    name: "ГРИБНОЙ",
    description: "БУЛОЧКА, САРДЕЛЬКА-ГРИЛЬ, ГРИБЫ, МАРИНОВАННЫЙ ЛУК, БЕЛЫЙ СОУС",
    price: 200,
    imageUrl: "https://your-cdn.com/images/masago-caviar.jpg",
  },
  {
    id: 91,
    category: "Hot-Dog",
    name: "В ЛАВАШЕ",
    description: "ЛАВАШ, САРДЕЛЬКА-ГРИЛЬ, КАПУСТА, МОРКОВЬ ПО-КОРЕЙСКИ, СВЕЖИЙ ОГУРЕЦ, ТОМАТЫ, МАРИНОВАННЫЙ ЛУК, СЫР, СОУС",
    price: 220,
    imageUrl: "https://your-cdn.com/images/shrimp.jpg",
  },
  {
    id: 92,
    category: "Cheesecake",
    name: "ФИСТАШКОВЫЙ",
    description: "150гр",
    price: 100,
    imageUrl: "assets/1MENUImages/150_ФИСТАШКОВЫЙ.jpg",
  },
  {
    id: 93,
    category: "Cheesecake",
    name: "ЯБЛОЧНЫЙ",
    description: "150гр",
    price: 140,
    imageUrl: "assets/1MENUImages/151_ЯБЛОЧНЫЙ.png",
  },
  {
    id: 94,
    category: "Cheesecake",
    name: "НЬЮ-ЙОРК КОКОС",
    description: "150гр",
    price: 100,
    imageUrl: "assets/1MENUImages/152_НЬЮ-ЙОРК_КОКОС.jpg",
  },
  {
    id: 95,
    category: "Coffee",
    name: "ДВОЙНОЙ ЭСПРЕССО",
    description: "60мл",
    price: 150,
    imageUrl: "https://your-cdn.com/images/salmon-chicken.jpg",
  },
  {
    id: 96,
    category: "Coffee",
    name: "ДВОЙНОЙ АМЕРИКАНО",
    description: "60мл",
    price: 140,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 97,
    category: "Coffee",
    name: "ЭСПРЕССО",
    description: "30мл",
    price: 130,
    imageUrl: "https://your-cdn.com/images/shiitake-mushrooms.jpg",
  },
  {
    id: 98,
    category: "Coffee",
    name: "АМЕРИКАНО",
    description: "100мл",
    price: 120,
    imageUrl: "https://your-cdn.com/images/sliced-eel.jpg",
  },
  {
    id: 99,
    category: "Coffee",
    name: "КАПУЧИНО",
    description: "100мл",
    price: 140,
    imageUrl: "https://your-cdn.com/images/cream-cheese-mix.jpg",
  },
  {
    id: 100,
    category: "Coffee",
    name: "ЛАТТЕ",
    description: "100мл",
    price: 140,
    imageUrl: "https://your-cdn.com/images/spicy-roll.jpg",
  },
  {
    id: 101,
    category: "Coffee",
    name: "МОЛОКО",
    description: "20мл",
    price: 25,
    imageUrl: "https://your-cdn.com/images/fried-salmon.jpg",
  },
  {
    id: 102,
    category: "Coffee",
    name: "СИРОПЫ",
    description: "СОЛЁНАЯ КАРАМЕЛЬ, МИНДАЛЬ, ВАНИЛЬ, ШОКОЛАД, КОКОС",
    price: 25,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  } ]